### PR TITLE
migrate to java14, junit5 and approval tests 4.0.2

### PR DESCRIPTION
**Pull request by LarsEckart**
I wish I could report that this is all working. but I get interesting errors:

>   "result": {
    "run_cyber_dojo_sh": {
      "stdout": {
        "content": [
          "To approve run : mv /sandbox/./HikerTest.hhgttg.received.txt /sandbox/./HikerTest.hhgttg.approved.txt\n",
          ".\n",
          "+-- JUnit Jupiter [OK]\n",
          "| '-- HikerTest [OK]\n",
          "|   '-- hhgttg() [X] expected:<[42]\n",
          "|         > but was:<[54]\n",
          "|         >\n",
          "'-- JUnit Vintage [OK]\n",
          "  '-- TestUtils [OK]\n",
          "    '-- initializationError [X] javax/mail/Message\n",
          "\n",
          "Failures (2):\n",
          "  JUnit Jupiter:HikerTest:hhgttg()\n",
          "    MethodSource [className = 'HikerTest', methodName = 'hhgttg', methodParameterTypes = '']\n",
          "    => junit.framework.ComparisonFailure: expected:<[42]\n",
          "> but was:<[54]\n",
          ">\n",
          "       junit.framework.Assert.assertEquals(Assert.java:100)\n",
          "       junit.framework.Assert.assertEquals(Assert.java:107)\n",
          "       junit.framework.TestCase.assertEquals(TestCase.java:260)\n",
          "       org.approvaltests.reporters.JunitReporter.report(JunitReporter.java:20)\n",
          "       org.approvaltests.reporters.FirstWorkingReporter.report(FirstWorkingReporter.java:32)\n",
          "       org.approvaltests.approvers.FileApprover.reportFailure(FileApprover.java:47)\n",
          "       org.approvaltests.Approvals.verify(Approvals.java:139)\n",
          "       org.approvaltests.Approvals.verify(Approvals.java:121)\n",
          "       org.approvaltests.Approvals.verify(Approvals.java:125)\n",
          "       org.approvaltests.Approvals.verify(Approvals.java:56)\n",
          "       [...]\n",
          "  JUnit Vintage:TestUtils:initializationError\n",
          "    => java.lang.NoClassDefFoundError: javax/mail/Message\n",
          "       java.base/java.lang.Class.getDeclaredMethods0(Native Method)\n",
          "       java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3244)\n",
          "       java.base/java.lang.Class.getMethodsRecursive(Class.java:3385)\n",
          "       java.base/java.lang.Class.getMethod0(Class.java:3371)\n",
          "       java.base/java.lang.Class.getMethod(Class.java:2120)\n",
          "       [...]\n",
          "     Caused by: java.lang.ClassNotFoundException: javax.mail.Message\n",
          "       java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)\n",
          "       java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)\n",
          "       java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:855)\n",
          "       java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)\n",
          "       [...]\n",
          "\n",
          "Test run finished after 224 ms\n",
          "[         4 containers found      ]\n",
          "[         0 containers skipped    ]\n",
          "[         4 containers started    ]\n",
          "[         0 containers aborted    ]\n",
          "[         4 containers successful ]\n",
          "[         0 containers failed     ]\n",
          "[         2 tests found           ]\n",
          "[         0 tests skipped         ]\n",
          "[         2 tests started         ]\n",
          "[         0 tests aborted         ]\n",
          "[         0 tests successful      ]\n",
          "[         2 tests failed          ]\n",
          "\n"
        ],
        "truncated": false
      },
      "stderr": {
        "content": [
          "An exception has occurred in the compiler (14.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.\n",
          "java.nio.file.AccessDeniedException: /approval/zipfstmp5701121991682355433.tmp\n",
          "\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)\n",
          "\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n",
          "\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)\n",
          "\tat java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)\n",
          "\tat java.base/java.nio.file.Files.newByteChannel(Files.java:375)\n",
          "\tat java.base/java.nio.file.Files.createFile(Files.java:652)\n",
          "\tat java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)\n",
          "\tat java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)\n",
          "\tat java.base/java.nio.file.Files.createTempFile(Files.java:872)\n",
          "\tat jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.createTempFileInSameDirectoryAs(ZipFileSystem.java:1575)\n",
          "\tat jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1718)\n",
          "\tat jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$close$9(ZipFileSystem.java:474)\n",
          "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:554)\n",
          "\tat jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:473)\n",
          "\tat jdk.compiler/com.sun.tools.javac.file.JavacFileManager$ArchiveContainer.close(JavacFileManager.java:655)\n",
          "\tat jdk.compiler/com.sun.tools.javac.file.JavacFileManager.close(JavacFileManager.java:733)\n",
          "\tat jdk.compiler/com.sun.tools.javac.main.DelegatingJavaFileManager.close(DelegatingJavaFileManager.java:140)\n",
          "\tat jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:180)\n",
          "\tat jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)\n",
          "\tat jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)\n"
        ],

AccessDeniedException: /approval/zipfstmp5701121991682355433.tmp\ is one odd thing, but the other is also the junit5 vintage initialization error due to  javax.mail

The javax.mail I can even reproduce in an empty project with just 1 junit5 test. The moment I have approvaltests 4.0.2 on the path, it happens. 

@JonJagger I'm bit puzzled right now, perhaps you've some insight or idea how to continue here?

### CODE REVIEW

**Comment by JonJagger** [comment]
Hi Lars,
that is an interesting error! Some goggling suggests the problem may be a missing jar file: javax.mail.jar
Once again, a big thank you for you help on these Java images.
Cheers :-)

**Comment by JonJagger** [comment]
Hi again Lars,
I've had a look and made some progress. The access denied problem is because javac is trying to create a temporary zip file in the `/approval` directory. That is a readonly directory because the whole file-system is, by default, a readonly file-system (for extra security) when the runner service runs `cyber-dojo.sh`. It seems pretty clear this is a bug. Javac should be creating temporary zip files off `/tmp`. I've looked to see if there are any `javac` options related to altering the tmp-path and can't see anything. For now a work-around for this is to copy the jar files to `/tmp` and use those in the classpath. I've tried using `ln -s /approval /tmp/approval` to avoid making the copy but it doesn't work. 
With `cyber-dojo.sh` like this
```
cd ${CYBER_DOJO_SANDBOX}
# Currently, using /approval in the classpath causes fatal errors such as
# java.nio.file.AccessDeniedException: /approval/zipfstmp5701121991682355433.tmp
# This is because /approval is a read-only file system.
# Working around this for now...
cp -r /approval /tmp
CLASSES=.:`ls /tmp/approval/*.jar | tr '\n' ':'`
```
I too get just the javax.mail exception.
There seems to be a `mail-1.4.7.jar` for this on the maven repository at
https://mvnrepository.com/artifact/javax.mail/mail/1.4.7
When I add that to /docker/jars then this problem goes away too.
The `./pipe_build_up_test.sh` run then gives an initial amber, but I think this is just a `red_amber_green.rb` regex issue.
Hope this helps
Thanks again
Jon

**Comment by LarsEckart** [comment]
Thank you! I'll get back to it :)

**Comment by JonJagger** [comment]
Was doing some work on the manifest.json for this today so I've upgraded.

**Pull request merged**
